### ISSUE TITLE
リソース設計をする

### ISSUE THREAD

**Issue by peno022** [peno022/kpi-tree-generator#21]
# リソース設計
Method | Path | Description
-- | -- | --
GET | / | トップ画面を表示（ログインしていればツリー一覧を、ログインしていなければサービスLPを表示する）
GET | /trees/play | ログインしていないユーザーのツリー編集画面
GET | /trees/[:tree_id]/edit | ログインしているユーザーのツリー編集画面
POST | /trees | ツリーを新規作成 or ログインなしで作成していたツリーを保存
PATCH | /trees/[:tree_id]| ツリーを更新
DELETE | /trees/[:tree_id]| ツリーを削除
GET | /trees/[:tree_id]/image| ツリーの画像をダウンロード
POST | /user | サインアップ
DELETE | /user | アカウント削除
GET | /terms-of-use | 利用規約画面を表示
GET | /privacy-policy | プライバシーポリシー画面を表示

## 補足
- フレームワークはRails7を利用し、ツリーの作成・編集画面のViewはReactで実装予定です。
- ログインはGoogleログインを利用する想定です。
- ログイン前後での画面挙動はCanvaを大いに参考にしています（https://www.canva.com/design/play）。
- エレベーターピッチ・ペーパープロトタイプはデータ設計のほうに記載しましたので、そちらをご参照ください。
  - https://github.com/peno022/kpi-tree-generator/issues/7
- ペーパープロトタイプの提出物にある「お問い合わせ」「ヘルプ」の導線は削除予定のため、該当ページは作成しない想定です。

## POST時のデータ構造

```json
{
  "tree": {
    "id": int
    "name": string,
    "root": object<Node>
  }
}
```

### Treeオブジェクト

| property name | type         | example                              | required? |
|---------------|--------------|--------------------------------------|-----------|
| id            | int       | 1 |           |
| name          | string       | My Tree                              | required  |
| root          | object<Node> | { Node1 }                            | required  |

### Nodeオブジェクト

| property name               | type          | example                              | required? |
|-----------------------------|---------------|--------------------------------------|-----------|
| id            | int       | 1 |           |
| name                        | string        | My Node                              | required  |
| value                       | number<float> |                                 1000 | required  |
| valueFormat                | enum          | 万                                   |           |
| unit                        | string        | 円                                   |           |
| isValueLocked             | boolean       |                 FALSE                | required  |
| operationRatioDenominator | integer       |                                    3 |           |
| operationRatioNumerator   | integer       |                                    2 |           |
| nextLayer                  | object<Layer> |                                      |           |

### Layerオブジェクト

| property name | type          | example                              | required? |
|---------------|---------------|--------------------------------------|-----------|
| id            | int       | 1 |           |
| operation     | enum          | addition                             |           |
| fraction      | number<float> |                                  0.1 |           |
| children      | array<Node>   | [{ Node1 }, { Node2 }]               | required  |

## その他実装時に考慮するべきこと

- 階層が深くなりすぎた時の懸念がないか。問題がでてきたら、階層の深さに上限を設定したほうがよいかも
- サーバーサイドでバリデーションをかける
- fractionで小数を扱うと、値をカットする/しないに関わらず、なにかしらどこかズレが生じるのを念頭におく

---
# タスク内容
## なぜやるか（背景）
- あとから修正が大変なので、先に設計をかためてから開発に進むようにする

## やること
- 下記の形式で一覧を作成して、レビューしてもらう

Method | Path | Description
-- | -- | --
xx|xx|xx

## 完了条件
- レビューが完了する

## 参考にするもの
- [リソース・データ設計 | FBC](https://bootcamp.fjord.jp/practices/229)
- [リソース設計を行う · Issue #25 · ot0m1/Srive](https://github.com/ot0m1/Srive/issues/25)

## 備考

**Comment by betachelsea** [comment]
@peno022 

拝見しました！Reactで動かすということで、利用者に露出するPathは上記でよさそうですね。Googleログインの実装を自分がしたことないので、もしかしたらその周りで必要に迫られてもう少し増えるかもしれませんが、実装時に柔軟に考えていただければOKかなと思いました。

ちょっと気になっている点としては、ER図側にある「Node」「Layer」「Operation」の情報を保存・更新していかないといけないと思うのですが、それらをどうやってReact -> サーバ側に送るのか…という部分が、この一覧からはまだ読み取れませんでした。
以下のどちらかかな？と思ったのですが、どうでしょう。

- 想定1: React側でモデルなどを駆使して保持しておき、DBへの反映は `/trees` へのPOST時に一気に提供する。 → 現状のPathで想定されているとしたらこちら？ この場合は、POST時に渡すデータ構造がキーになってきそうなので、その辺りを"リソース設計"の一環として、詳しく伺った方が良いかなと思っています。
- 想定2: 操作のたびにAPIでサーバ側に更新を伝えて、都度React側はサーバに保持された内容の表示に徹底する。→ こちらだと、ユーザには露出しないけどサーバ<->ReactでやりとりするためのPathをもうちょっと定義しておいた方が良いかなと考えます。

他の想定もあるかなと思いますので、詳しく伺えればと思います！
返信お待ちしております〜  :pray:

**Comment by peno022** [comment]
@betachelsea 
ご確認いただきありがとうございます！
想定2のほうはそもそも考えられていなかったです・・ありがとうございます！
改めて検討したうえで1がいいかなと思ったので、理由を下記に記載します。見当違いになってそうな点や、他の比較観点があれば、コメントいただけないでしょうか🙇‍♀️

1がよさそうと考えた背景：

  - ログイン前とログイン後で、保存方式をそろえられたほうがシンプルで良いかなと思ったため
    - ログイン前のツリー作成の場合は、まだユーザーがないためツリーは保存できない。React側で保持して画面表示
    - ログインしたらログイン前に保持していたツリーを一気に保存
    - ログイン後は、操作中はReactで保持し、保存ボタンを押したタイミングで同じように一気にツリーを保存
  - 各ノードをちょこちょこ変更してシミュレーションしてみるような操作が多い想定のため、都度サーバーと通信があると表示が遅くなってしまうのでは？を懸念したため

このまま1で進められそうとなったら、POST時のデータ構造を引き続き検討していこうと思います！

**Comment by betachelsea** [comment]
@peno022  検討ありがとうございます！ 想定1か2か、というところに明確な解は無く、どちらもやろうと思えばできるので、peno022さんご自身がメリデメを検討して「こちらでいこう！」と思った方で良いとおもいます :+1:  

背景について、自分からも意見を共有します。

> ログイン前とログイン後で、保存方式をそろえられたほうがシンプルで良いかなと思ったため

- こちら、揃ったほうがシンプルというのは同意です〜。
- ツリー情報をjsのオブジェクトとして保持する場合は、リロードされたりブラウザを閉じられたりすると全部失われてしまうという点は許容もしくは対策をしておく必要があるかなと思いました。
  - `onbeforeunload` イベントなどを活用して警告を出すなどはできそうですね。
  - もしくは localStorage に一時的に保持するとか？ うーん、やりようは色々ありますね。
- ちなみに、「ユーザがないためツリーは保存できない」については、「ユーザ無しでもツリーの保存を許す」にすれば一応回避可能なので、"未ログインだから不可能"とは考えなくても良いかなと思いました。(この辺りは issue #7 でも話がありそうですね〜 :eyes: )

> 各ノードをちょこちょこ変更してシミュレーションしてみるような操作が多い想定のため、都度サーバーと通信があると表示が遅くなってしまうのでは？を懸念したため

- こちらも確かに懸念材料だと思いました〜 :eyes: 
- (とはいえ、データがよほど巨大でなければ、ミリ秒単位の話であって、人間が感じ取れるほどの遅延を心配するかどうか…というところもあるかもとも思いました。)


今回は1でいこうと思われたとのことで、それでしたら、Pathについては現状 ⬆️ のもの で問題ないと考えます。
POST時のデータ構造は、データ設計( issue #7 )が着地しないと検討していくのも難しいと思いますので、一旦は #7 でお話を進めましょう！よろしくお願いします〜 :+1:

**Comment by peno022** [comment]
@betachelsea 
ご確認ありがとうございます！1の方針でいきたいと思います。
そのうえで、データ設計（ https://github.com/peno022/kpi-tree-generator/issues/7 ）のほうを先にかためてから、こちらの検討に戻ってこられればと思います🙏

**Comment by peno022** [comment]
@betachelsea 
データ設計（ https://github.com/peno022/kpi-tree-generator/issues/7 ）からこちらに戻ってきました！
ご確認をお願いいたします🙏

POST時のリクエストボディは、下記のような形式で考えています。
PATCHのときは、作成済みのTree, NodeにはIDのプロパティを追加する想定です。

```json
{
  "tree": {
    "name": string,
    "root": object<Node>
  }
}
```
### Treeオブジェクト

| property name | type         | example   | required? |
|---------------|--------------|-----------|-----------|
| name          | string       | My Tree   | required  |
| root          | object<Node> | { Node1 } | required  |

### Nodeオブジェクト

| property name               | type          | example                | required? |
|-----------------------------|---------------|------------------------|-----------|
| name                        | string        | My Node                | required  |
| value                       | number<float> |                   1000 | required  |
| value_format                | enum          | 万                     |           |
| unit                        | string        | 円                     |           |
| is_value_locked             | boolean       |          FALSE         | required  |
| operation                   | enum          | addition               |           |
| fraction                    | number<float> |                    0.1 |           |
| operation_ratio_denominator | integer       |                      3 |           |
| operation_ratio_numerator   | integer       |                      2 |           |
| children                    | array<Node>   | [{ Node1 }, { Node2 }] | required  |

### 悩みポイント

- Nodeのchildrenが永遠に入れ子になること。サーバー側ではなんらか再帰的に処理できるので問題ないはず？と思いつつ、考慮しておくべき点がないかどうか気にしています。
- Layerは表さず、親ノードにoperation, fractionの情報を入れていること。分かりづらくないかを気にしています。

### サンプル
```
                            売上金額
                          （1000万円）
                  /                          \
              新規顧客売上         +         既存顧客売上
              （400万円）                    （600万円）
              /      \                     /         \
      新規顧客数    ×   顧客単価          事業A売上   +  事業B売上
      （4000人）         （1000円）        （250万円）         （350万円）
     /         \
自HP経由(1/4)  広告経由(3/4)
（1000人）     （3000人）


```

```json
{
  "tree": {
    "name": "Tree 1",
    "root": {
      "name": "売上金額",
      "value": 1000,
      "value_format": "万",
      "unit": "円",
      "is_value_locked": true,
      "operation": "addition",
      "children": [
        {
          "name": "新規顧客売上",
          "value": 400,
          "value_format": "万",
          "unit": "円",
          "is_value_locked": false,
          "operation": "multiplication",
          "children": [
            {
              "name": "新規顧客数",
              "value": 4000,
              "value_format": "",
              "unit": "人",
              "is_value_locked": false,
              "operation": "distribution",
              "children": [
                {
                  "name": "自HP経由",
                  "value": 1000,
                  "value_format": "",
                  "unit": "人",
                  "is_value_locked": false,
                  "operation_ratio_denominator": 4,
                  "operation_ratio_numerator": 1,
                  "children": []
                },
                {
                  "name": "広告経由",
                  "value": 3000,
                  "value_format": "",
                  "unit": "人",
                  "is_value_locked": false,
                  "operation_ratio_denominator": 4,
                  "operation_ratio_numerator": 3,
                  "children": []
                }
              ]
            },
            {
              "name": "顧客単価",
              "value": 1000,
              "value_format": "",
              "unit": "円",
              "is_value_locked": false,
              "children": []
            }
          ]
        },
        {
          "name": "既存顧客売上",
          "value": 600,
          "value_format": "万",
          "unit": "円",
          "is_value_locked": false,
          "operation": "addition",
          "children": [
            {
              "name": "事業A売上",
              "value": 250,
              "value_format": "万",
              "unit": "円",
              "is_value_locked": false,
              "children": []
            },
            {
              "name": "事業B売上",
              "value": 350,
              "value_format": "万",
              "unit": "円",
              "is_value_locked": false,
              "children": []
            }
          ]
        }
      ]
    }
  }
}

```

**Comment by betachelsea** [comment]
@peno022 
リクエストボディありがとうございます！かなり具体的になってきましたね :+1:  おおむね問題なさそうと思いつつも、ちょっと気になったところもあったので、もう1往復くらいやりとりさせていただければと思います :pray: 

まず、悩みポイントについて書いてみます。

# 悩みポイント

## Nodeのchildrenが永遠に入れ子になること
これはデータ設計のissue #7 でも話題に出ましたが、階層の深さを設定するのがひとつの回避策になってきそうですね。 #7 の結論としては一旦は制限を設けず様子を見るということになったかなと思っており、また問題にぶつかったら考えるとかでも良いかなと思います。誤って再帰の構造になってしまわないようにするという点では、すでに親としての役割を持つノードを子として設定しないように、というのは念の為バリデーション設定しておくのが良さそうですね。

## Layerは表さず、親ノードにoperation, fractionの情報を入れていること

これも悩みどころですね。データベースに更新を投げることを考えると、nodeの情報とoperation, fraction が同列になっていて、かつchildrenも同列にいるので、 node単体の情報を抜き出す というときにちょっと手間かなと感じました。ただ、DBに新規作成/更新をリクエストするときに必要なデータ形式を把握していないので、一概には言えないところです。( よく考えたら、フロントはReactとしても、サーバサイド(DBとのやりとり)は何のフレームワークを使うのか聞きそびれておりました :bow:  )
この辺りは実装しつつ、コードが綺麗になりやすい・書きやすいというところに寄せて、想定との差を埋めていく必要はありそうだと思いました。このとき、実装の途中で「やっぱりこう変更しよう」となったら、ちゃんと事前に考えておいた想定の資料も更新をやっておくと、一手間ですがいざという時にさっと問題点を調べることにつながって便利だと思います :sparkles: 

just idea なので聞き流していただければと思うのですが、もしモデルの形に従って組み立てるなら、次のようにするのもありかなと思いました。

```json
# 途中からですが

{
  "node": {
    "name": "売上金額",
    "value": 1000,
    "value_format": "万",
    "unit": "円",
    "is_value_locked": true,
  },
  "layer": { "operation": "addition" },
  "children:": [
    {
      "node:" {
        # ...略...
      }
    },
    {
      # ...略...
    }
  ]       
}
```

それか構造的にはLayerのなかにchildrenがいるような形なのでこうとか…？

```json
# ちょっとインデント汚いですがご容赦…。

{
  "tree": {
    "name": "Tree 1",
    "root": {
        "node": { ... },
        "next_layer": {
          "operation": "addition",
          "fraction": 0.1,
          "children": [
            {
                "node": { ... },
                "next_layer": {
                    "operation": "addition",
                    "fraction": 0.1,
                    "children": [ ... ]
                }
            },
            {
                "node": { ... }
            }
          ]
        }
    }
  }
}
```

なんにせよ、全体像を常に把握しつつも、実装序盤は特に変化を恐れずにやるしかないかもしれません！ :sweat_smile: 

# "砦" をどこにおくか？

さきほど、チラと書いた「サーバサイドって何を使うんだっけ」というところにもしかすると関連するかもしれませんが、『不整合のエラーを出す』のは React に判断させる or サーバサイドに判断させる、のどちらを想定されているでしょうか。より安全なのはサーバサイド側かなと思います。サーバサイドがリクエストされたデータを鵜呑みにしてDBに保存するだけですと、リクエストされたデータが改竄されていた場合に問題になります。綺麗なデータベースを維持するためには、サーバサイドを"最後の砦"としてしっかりバリデーションをかけておくのが必要かなと思いました。特に今回のサービスはデータ間の整合性ができるだけ取れていたほうが、もし将来的に改修するときにも苦労が減ってよいかなと感じています。

Reactとサーバサイドで、二重に検査系のロジックを書くのが手間なのと、Reactは表示回りに心を砕く必要が出てきそうなので、できれば難しいことはサーバサイド側で済ませた方が良いのではないかと思いますが、このサイズのjsonをなんとかしようとおもったら、リクエストするほう(React?)もちょっと頑張ってもらわないといけなさそうだという感想がありました。
Reactと親和性のあるサーバサイドを使えば、コード共通化できるとかあるかもしれないですが、自分がこの辺あんまり知識なく…すみません :sob: :bow: 

色々と作り込む前に、データの受け渡しが想定通りにできるか、というところの検証を済ませてもらうと良いかもと思いました〜。 :eyes: 

# その他気になったこと
- fraction(端数)、整数だけ持つみたいな印象があったのですが、例で `0.1` と小数点の値がきていたのでちょっと驚きました。サンプルのjsonには fraction の表記が無いですね。仕様として予定しているなら、その予定内容をフルに使った形のサンプルを用意しておくと、実装の時に参考になって便利なのでオススメします :+1:  
- IDもある/無しが混じることがあり得ると思うので (特に保存済みのツリーに新しい子ノードを追加した、など) IDを入れると仮にどうなるのかというのも確認しておいても良いかなと思いました。それでいうと、LayerのIDの入れ先が現状のjsonには無いので、工夫してもらった方が良いかもと感じました。(Layerの更新をどうするかという点とも紐づくので、一概には言えないかもしれませんが)

**Comment by peno022** [comment]
@betachelsea 
色々な観点からご指摘くださいってありがとうございます！
今の段階で色々洗い出せており非常に助かります🙇‍♀️

>なんにせよ、全体像を常に把握しつつも、実装序盤は特に変化を恐れずにやるしかないかもしれません！ 😅

とコメントいただいているとおり、私も、
この段階で決めきれないことは、実装進めていて不都合が出るようであればそのタイミングでまた考え直そうかなあ、という気持ちでいます。

# サーバーサイド含めた構成について

最初に説明できておらずすみません🙇‍♀️

サーバーサイドはRailsを想定しています。
現在利用しているバージョンは7.0.4です。

フロントエンドと完全に切り離す形ではなく、RailsのViewをReactで作成する想定でサンプルアプリを作成していました。

背景：

- できるだけRailsを使いたい
  - プラクティスで学んできたため（別な技術の学習にさらに時間をかけるよりかは、早く作りたい）
  - せっかくRailsの有識者が多いコミュニティのため
- ツリーの操作、数値の更新はサクサク動いてほしい
  - SPAで作るのが良いのかな → React使ってみよう

# Nodeのchildrenが永遠に入れ子になること
> 階層の深さを設定するのがひとつの回避策になってきそうですね。 https://github.com/peno022/kpi-tree-generator/issues/7 の結論としては一旦は制限を設けず様子を見るということになったかなと思っており、また問題にぶつかったら考えるとかでも良いかなと思います。

> 誤って再帰の構造になってしまわないようにするという点では、すでに親としての役割を持つノードを子として設定しないように、というのは念の為バリデーション設定しておくのが良さそうですね

ありがとうございます！　念頭に置いて進めます！
やっぱり階層の深さに制限設けたほうがよさそう〜という気持ちが出てきていますが、実装しながら考えられればと思います。

# Layerは表さず、親ノードにoperation, fractionの情報を入れていること

> それか構造的にはLayerのなかにchildrenがいるような形なのでこうとか…？

2つめに例にあげてくださった形が、私としても分かりやすくてよさそうと感じました。ありがとうございます！
後述のサンプルも、こちらの形で書き換えてみました。

また、こちらのご指摘もいただいたので
> IDもある/無しが混じることがあり得ると思うので (特に保存済みのツリーに新しい子ノードを追加した、など) IDを入れると仮にどうなるのかというのも確認しておいても良いかなと思いました。それでいうと、LayerのIDの入れ先が現状のjsonには無いので、工夫してもらった方が良いかもと感じました。

IDの項目も追加しています。

※加えて、

Treeオブジェクト：
| property name | type         | example                              | required? |
|---------------|--------------|--------------------------------------|-----------|
| id            | string       | 4b78f54f-c8c1-4c0b-8cd4-cca1dc845b36 |           |
| name          | string       | My Tree                              | required  |
| root          | object<Node> | { Node1 }                            | required  |

Nodeオブジェクト：
| property name               | type          | example                              | required? |
|-----------------------------|---------------|--------------------------------------|-----------|
| id                          | string        | 8fbed9ba-d06a-479e-8b22-21b547406bdf |           |
| name                        | string        | My Node                              | required  |
| value                       | number<float> |                                 1000 | required  |
| valueFormat                | enum          | 万                                   |           |
| unit                        | string        | 円                                   |           |
| isValueLocked             | boolean       |                 FALSE                | required  |
| operationRatioDenominator | integer       |                                    3 |           |
| operationRatioNumerator   | integer       |                                    2 |           |
| nextLayer                  | object<Layer> |                                      |           |


Layerオブジェクト：
| property name | type          | example                              | required? |
|---------------|---------------|--------------------------------------|-----------|
| id            | string        | 5cf877d3-fc44-4485-83f7-f57b97d528fb |           |
| operation     | enum          | addition                             |           |
| fraction      | number<float> |                                  0.1 |           |
| children      | array<Node>   | [{ Node1 }, { Node2 }]               | required  |


# "砦" をどこにおくか？

このチェックはここで、このチェックはここで・・というほど現段階で具体的に想定していなかったです。
ざっくりした方針でも大丈夫でしょうか・・？
下記のように考えています。

- 最後の砦としては、Rails側で全てのチェックをかける
- 入力時点でチェックできそうなものについては、React側でもチェックをする
  - 画面上の入力必須項目など

# fractionについて

- 使える数値は小数第二位まで、など固定で切ってしまおうかなと思っているので、その場合は端数も小数第二位までは発生しうるかなと思っています。
- 後述のサンプルのデータにも、端数を含めるように修正しました。


# リクエストボディのサイズ上限について

全く考慮していませんでした・・ありがとうございます！
いくつか検索してみて、たとえば[core - Apache HTTP サーバ バージョン 2.4](https://httpd.apache.org/docs/2.4/ja/mod/core.html)のサイトには下記のような項目がありました。上限値があることは念頭に起き、どのくらいのサイズになっているか実装すすめる中でも意識するという形かなと思います。

> このディレクティブは、リクエストボディに許されるバイト数、bytes を 0 (無制限を意味します) から 2147483647 (2GB) までの数値で指定します。

# サンプル（改）

- IDを項目に含めました。PATCH時はここに値が入ることを想定しています。
- Layerを表現する形で書き直しました。
- fractionの項目をサンプルに含めました。

```ini
                                                         売上金額
                                                       （1000万円）
                                           /                                  \
                                    新規顧客売上         +                     既存顧客売上
                                    （400万円）                               （600万円）
                                /                 \                         /         \
                           新規顧客数          ×       顧客単価          事業A売上  +    事業B売上
                          （4000人）                   （1000円）       （250万円）     （350万円）
                        /           /                      \                       
媒体A経由(1/3) + 媒体B経由(1/3) + 広告経由(1/3) + 端数
 （1333 人）      （1333 人）          （1333 人）        （1）


```

```json
{
  "tree": {
    "treeId": "",
    "name": "Tree 1",
    "root": {
      "nodeId": "",
      "name": "売上金額",
      "value": 1000,
      "valueFormat": "万",
      "unit": "円",
      "isValueLocked": true,
      "nextLayer": {
        "operation": "addition",
        "fraction": 0,
        "children": [
          {
            "nodeId": "",
            "name": "新規顧客売上",
            "value": 400,
            "valueFormat": "万",
            "unit": "円",
            "isValueLocked": false,
            "nextLayer": {
              "operation": "multiplication",
              "fraction": 0,
              "children": [
                {
                  "nodeId": "",
                  "name": "新規顧客数",
                  "value": 4000,
                  "valueFormat": "",
                  "unit": "人",
                  "isValueLocked": false,
                  "nextLayer": {
                    "operation": "distribution",
                    "fraction": 1,
                    "children": [
                      {
                        "nodeId": "",
                        "name": "自HP経由",
                        "value": 1000,
                        "valueFormat": "",
                        "unit": "人",
                        "isValueLocked": false,
                        "operationRatioDenominator": 4,
                        "operationRatioNumerator": 1,
                        "nextLayer": {}
                      },
                      {
                        "nodeId": "",
                        "name": "広告経由",
                        "value": 3000,
                        "valueFormat": "",
                        "unit": "人",
                        "isValueLocked": false,
                        "operationRatioDenominator": 4,
                        "operationRatioNumerator": 3,
                        "nextLayer": {}
                      }
                    ]
                  }
                },
                {
                  "nodeId": "",
                  "name": "顧客単価",
                  "value": 1000,
                  "valueFormat": "",
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                }
              ]
            }
          },
          {
            "nodeId": "",
            "name": "既存顧客売上",
            "value": 600,
            "valueFormat": "万",
            "unit": "円",
            "isValueLocked": false,
            "nextLayer": {
              "operation": "addition",
              "fraction": 0,
              "children": [
                {
                  "nodeId": "",
                  "name": "事業A売上",
                  "value": 250,
                  "valueFormat": "万",
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                },
                {
                  "nodeId": "",
                  "name": "事業B売上",
                  "value": 350,
                  "valueFormat": "万",
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                }
              ]
            }
          }
        ]
      }
    }
  }
}

```

**Comment by peno022** [comment]
@betachelsea 

↑上記に一点補足が漏れていたので追記させてください。

[Google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format)を読んだところ、プロパティ名はキャメルケースにすべしという記載があったので、`is_value_locked` → `isValueLocked`のように変更しています🙏

**Comment by betachelsea** [comment]
@peno022 
返信ありがとうございます！ 👍

RailsとReactなんですね！自分も主にRailsで仕事してるので、イメージつきやすいです。FBC自体も同じ構造なので参考にしやすくて良いのではと思います 👍 

入れ子の件、砦の件についても、あとは実装しながら方針が変わっていくこともあると思うので、都度書きづらいな〜と思うところがあれば良いやり方を模索してみてくださいね！

サンプル(改)のJSONを改めて拝見して、気になった点を共有します👀 再度チェックしてみていただけますか！ 🙏 

- [MUST] 新規顧客4000人の下の、媒体A+B+広告+端数1の想定がJSONと異なるようなので、見直しをお願いします！
- [IMO] fractionで小数を扱うと、値をカットする/しないに関わらず、なにかしらどこかズレるということは念頭に置いて実装していただければと思います！プログラムでの少数の取り扱いは本当に鬼門です…  (だから税率とかほんとイヤ…ぶつぶつ…あっなんでもないです… 😅 ) 自分が初めに仕様を見て思ったところは、今回のサンプルのように「整数の合計値を作るための余剰の値(整数)」を入れる、というイメージだったので、小数を扱う想定でしたら、具体的にどういうシーンで少数がくるのかは考えておいてもいいかなと思いました👀 
- [IMO] idにハッシュ値的な文字列が入る予定のようですが、Railsのレールに則ると、idはインクリメントされていく数字がDBによって自動的に割り振られるケースが多いので、特別に文字列にしたい理由がなければintegerで考えると楽そうです。
- [IMO] 値なしの部分を空文字列で表現されているようですが、ある意味で「空の文字列」という値を使っている状態なので、null を活用するのもありかもと思いました。

**Comment by peno022** [comment]
@betachelsea 

ご確認ありがとうございます！
結論を残しておく用に、ここまでのコメントのやりとりを踏まえて、descriptionの欄も追記しましたm

下記、再度になりお手数ですがご確認をお願いします。
小数の扱いについてだけ懸念が残っています。。

# IDについて

> [IMO] idにハッシュ値的な文字列が入る予定のようですが、Railsのレールに則ると、idはインクリメントされていく数字がDBによって自動的に割り振られるケースが多いので、特別に文字列にしたい理由がなければintegerで考えると楽そうです。

特別な理由なかったです・・ご指摘ありがとうございます。
integerで設定します。

# 小数のfractionについて

> [IMO] fractionで小数を扱うと、値をカットする/しないに関わらず、なにかしらどこかズレるということは念頭に置いて実装していただければと思います！プログラムでの少数の取り扱いは本当に鬼門です… (だから税率とかほんとイヤ…ぶつぶつ…あっなんでもないです… 😅 ) 自分が初めに仕様を見て思ったところは、今回のサンプルのように「整数の合計値を作るための余剰の値(整数)」を入れる、というイメージだったので、小数を扱う想定でしたら、具体的にどういうシーンで少数がくるのかは考えておいてもいいかなと思いました👀

valueが小数のノードの作成を許す以上は、それが分割されることもあるので、小数になる想定は必須かなと思っていました。
ズレが恐ろしいですが、避けようがないですかね・・？

例）

```
       通知開封数目標
        （3.5回/週）
       /          \
   送信数 ×   開封率    + 端数
  (300回)    (1.2%)     (-0.1)

```

# サンプル（改2）

> [MUST] 新規顧客4000人の下の、媒体A+B+広告+端数1の想定がJSONと異なるようなので、見直しをお願いします！

見落しあり申し訳ないです。JSONを修正しました。

また、

> [IMO] 値なしの部分を空文字列で表現されているようですが、ある意味で「空の文字列」という値を使っている状態なので、null を活用するのもありかもと思いました。

空文字については検討せず選択してしまっていたので、nullに修正しました。ご指摘ありがとうございます。

```
                                                         売上金額
                                                       （1000万円）
                                           /                                  \
                                    新規顧客売上         +                     既存顧客売上
                                    （400万円）                                 （600万円）
                                /                 \                         /         \
                           新規顧客数          ×       顧客単価          事業A売上  +    事業B売上
                          （4000人）                   （1000円）          （250万円）     （350万円）
          /         /              \          \
媒体A経由(1/3) + 媒体B経由(1/3) + 広告経由(1/3) + 端数
（1333 人）         （1333 人）       （1333 人）     （1）


```

```json
{
  "tree": {
    "treeId": null,
    "name": "Tree 1",
    "root": {
      "nodeId": null,
      "name": "売上金額",
      "value": 1000,
      "valueFormat": "万",
      "unit": "円",
      "isValueLocked": true,
      "nextLayer": {
        "operation": "addition",
        "fraction": 0,
        "children": [
          {
            "nodeId": null,
            "name": "新規顧客売上",
            "value": 400,
            "valueFormat": "万",
            "unit": "円",
            "isValueLocked": false,
            "nextLayer": {
              "operation": "multiplication",
              "fraction": 0,
              "children": [
                {
                  "nodeId": null,
                  "name": "新規顧客数",
                  "value": 4000,
                  "valueFormat": null,
                  "unit": "人",
                  "isValueLocked": false,
                  "nextLayer": {
                    "operation": "distribution",
                    "fraction": 1,
                    "children": [
                      {
                        "nodeId": null,
                        "name": "媒体A経由",
                        "value": 1333,
                        "valueFormat": null,
                        "unit": "人",
                        "isValueLocked": false,
                        "operationRatioDenominator": 3,
                        "operationRatioNumerator": 1,
                        "nextLayer": {}
                      },
                      {
                        "nodeId": null,
                        "name": "媒体B経由",
                        "value": 1333,
                        "valueFormat": null,
                        "unit": "人",
                        "isValueLocked": false,
                        "operationRatioDenominator": 3,
                        "operationRatioNumerator": 1,
                        "nextLayer": {}
                      },
                      {
                        "nodeId": null,
                        "name": "広告経由",
                        "value": 1333,
                        "valueFormat": null,
                        "unit": "人",
                        "isValueLocked": false,
                        "operationRatioDenominator": 3,
                        "operationRatioNumerator": 1,
                        "nextLayer": {}
                      }
                    ]
                  }
                },
                {
                  "nodeId": null,
                  "name": "顧客単価",
                  "value": 1000,
                  "valueFormat": null,
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                }
              ]
            }
          },
          {
            "nodeId": null,
            "name": "既存顧客売上",
            "value": 600,
            "valueFormat": "万",
            "unit": "円",
            "isValueLocked": false,
            "nextLayer": {
              "operation": "addition",
              "fraction": 0,
              "children": [
                {
                  "nodeId": null,
                  "name": "事業A売上",
                  "value": 250,
                  "valueFormat": "万",
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                },
                {
                  "nodeId": null,
                  "name": "事業B売上",
                  "value": 350,
                  "valueFormat": "万",
                  "unit": "円",
                  "isValueLocked": false,
                  "nextLayer": {}
                }
              ]
            }
          }
        ]
      }
    }
  }
}

```

**Comment by betachelsea** [comment]
サンプル修正ありがとうございます！
null, ID についてもまた実装するときにでも、思い出してもらえればと思います〜。

少数のfractionについて、具体例助かりました！そういうケースがあり得るんですね。
ちょっと苦労しそうな例がないか考えてみたのですが、掛け算に端数を合わせる場合は無理数が出るケースはもしかして無い…？ 
少数で整合性のことを考えるときにボトルネックになるのが無理数だと思ったのですが、今回のツールは無理数になりそうなところを端数でいかに帳尻を合わせるように計算させるか（それを出来るだけ人間を悩ませずに）…というところなのかも、と改めて発見がありました :sparkles: 

一通り伺って、今の時点での懸念点はだいたい洗い出せたように思うので、確認OKとさせてもらいますね！ 🎉 
実装してみたら、当初の想定と違った…と感じるところは多々出てくると思いますので、よりよい実装を目指して柔軟に進めていってくださいね。ファイトです〜！ 🚀

**Comment by peno022** [comment]
レビューありがとうございました！！！
実装前に注意点洗い出せて大変助かりました！進めていきます💪
